version: '3.8'
services:

  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    volumes:
      - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
      - test_volume:/var/lib/root/data


  app:
    build: .
    
    ports:
      - "7777:7777"
    volumes:
      - ./:/app/
      - /app/node_modules

volumes:
  test_volume:
    {}
  























  # # PostgreSQL pgAdmin panel accessible at http://localhost:16543/
  # pgadmin-compose:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "placeholder@example.com"
  #     PGADMIN_DEFAULT_PASSWORD: "fakepassword123!"
  #   ports:
  #     - "16543:80"
  #   depends_on:
  #     - postgres